import { ArrowRight, Award, Eye, Flag, Gem, Lightbulb, Target, Users } from "lucide-react";
import { Link } from "react-router-dom";
import Seo from "@/components/Seo";
import { AnimatedSection } from "@/components/AnimatedSection";
import chairmanImage from "@/assets/Chairman.png";
import heroCorporate from "@/assets/hero-corporate.jpg";
import retailStore from "@/assets/retail-store.jpg";
import manufacturingImage from "@/assets/sector-manufacturing-v2.jpg";
import hospitalityImage from "@/assets/sector-hospitality-v2.jpg";
import { awards, coreValues, journey, leadership } from "@/data/siteContent";

const stats = [["11", "Group companies"], ["300+", "Employees"], ["250+", "Distributors"]];
const valueIcons = [Gem, Users, Lightbulb, Flag];
const Label = ({ children }: { children: React.ReactNode }) => <p className="text-xs font-bold uppercase tracking-[.18em] text-[#315f9f]">{children}</p>;
const Rule = () => <div className="mt-4 h-0.5 w-12 bg-[#d79a22]" />;

const About = () => (
  <div className="min-h-screen overflow-hidden bg-[#fbfaf7] text-[#102746]">
    <Seo title="About Supun Group of Companies | Our Story Since 1978" description="Discover the story, leadership, vision, journey and values of Supun Group of Companies, a Sri Lankan family-run group with roots dating to 1978." keywords="Supun Group history, Mohamed Fareed, M.F.M. Kaleel, Sri Lanka manufacturing group, Supun Group leadership" />

    <section className="relative isolate min-h-[620px] overflow-hidden bg-[#102746] md:min-h-[690px]">
      <img src={heroCorporate} alt="A modern Sri Lankan business building" className="absolute inset-0 -z-20 h-full w-full object-cover" />
      <div className="absolute inset-0 -z-10 bg-gradient-to-r from-white via-white/90 to-white/5 md:via-white/70" />
      <div className="container mx-auto flex min-h-[620px] items-center px-4 pb-16 pt-36 md:min-h-[690px] md:pt-40">
        <AnimatedSection animation="fade" duration={550} triggerOnce={false}><div className="max-w-2xl"><Label>Our story continues</Label><h1 className="mt-5 text-5xl font-semibold normal-case leading-[1.03] tracking-[-.045em] sm:text-6xl md:text-7xl">Built in Sri Lanka.<br />For a brighter tomorrow.</h1><p className="mt-6 max-w-lg text-base leading-7 text-[#3e536e] md:text-lg">Two generations. Multiple industries. One unwavering commitment to quality, innovation and Sri Lankan pride.</p><Rule /></div></AnimatedSection>
      </div>
      <div className="absolute bottom-8 right-6 hidden border-l border-white/50 pl-5 text-[10px] font-bold uppercase leading-6 tracking-[.2em] text-white md:block">People<br />Products<br />Possibilities</div>
    </section>

    <section id="story" className="scroll-mt-24 bg-white py-14 md:py-20"><div className="container mx-auto grid gap-10 px-4 lg:grid-cols-[.9fr_1.1fr] lg:items-center">
      <AnimatedSection animation="fade" duration={500} triggerOnce={false}><Label>Our story</Label><h2 className="mt-3 text-4xl font-semibold normal-case tracking-[-.04em] md:text-5xl">From trading goods to making them.</h2><Rule /><div className="mt-6 space-y-4 text-sm leading-7 text-[#53647a] md:text-base"><p>A family-run business since 1978, Supun Group of Companies began when Mr. Mohamed Fareed founded Supun Traders in Colombo, trading household goods for Sri Lankan homes. In 1999, his son, current Chairman Mr. M.F.M. Kaleel, took over the business and formalized it as the Supun Group of Companies, setting the Group on a new course: from trading goods to manufacturing them.</p><p>Through structured growth, the Group is now involved in manufacturing, retail, distribution, and hospitality, each held to the same standard of quality and Sri Lankan craftsmanship. Under the Camy name, Supun manufactures SLS-certified motorcycle helmets, non-stick cookware, air conditioners, and fans entirely in its own factories, reaching homes across the island through Supun Super Center and a network of 250+ distributors.</p><p>Supun Arcade Residency extends the Group into hospitality with luxury serviced apartments in central Colombo, alongside Area 56, its rooftop dining venue.</p><p>With an eye on the future and a continued focus on Sri Lankan manufacturing, the Group credits its growth to two generations of family leadership and a shared commitment to quality, innovation, and Sri Lankan pride, in everything it builds.</p></div><div className="mt-7 grid grid-cols-3 gap-3">{stats.map(([value, label]) => <div key={label} className="border-l-2 border-[#d79a22] pl-3"><strong className="text-2xl font-semibold md:text-3xl">{value}</strong><p className="mt-1 text-[10px] uppercase tracking-wide text-[#6a788a]">{label}</p></div>)}</div></AnimatedSection>
      <AnimatedSection animation="fade" duration={550} triggerOnce={false}><div className="relative mx-auto max-w-2xl pb-10 pl-4 sm:pl-12"><img src={retailStore} alt="The Group's retail beginnings" className="h-[300px] w-[78%] -rotate-2 border-[8px] border-white object-cover shadow-xl grayscale" /><img src={heroCorporate} alt="Supun Group today" className="absolute bottom-0 right-0 h-[220px] w-[58%] rotate-3 border-[8px] border-white object-cover shadow-xl" /><div className="absolute right-2 top-1 rounded-full bg-[#f3ead9] px-5 py-4 text-center text-[10px] font-bold uppercase leading-5 tracking-[.12em] text-[#8b682a]">From Sri Lanka<br />to Sri Lankans</div></div></AnimatedSection>
    </div></section>

    <section id="chairman" className="scroll-mt-24 bg-white"><div className="container mx-auto grid lg:grid-cols-[.72fr_1.28fr] lg:items-stretch">
      <AnimatedSection animation="fade" duration={500} triggerOnce={false}><div className="flex h-full flex-col items-center justify-center bg-white px-6 py-12 text-center lg:px-10"><img src={chairmanImage} alt="M.F.M. Kaleel, Chairman" className="max-h-[500px] w-full max-w-[430px] object-contain object-center" /><div className="mt-5 w-full max-w-[430px] border-t border-[#102746]/10 pt-5"><p className="text-xl font-medium leading-snug text-[#102746]">“Innovation and creativity for a better tomorrow.”</p><p className="mt-4 text-sm font-semibold">M.F.M. Kaleel</p><p className="text-xs text-[#6b7889]">Chairman</p></div></div></AnimatedSection>
      <AnimatedSection animation="fade" duration={550} triggerOnce={false}><article className="flex h-full flex-col justify-center bg-white p-7 sm:p-10 lg:p-14"><Label>Chairman’s message</Label><h2 className="mt-3 text-4xl font-semibold normal-case tracking-[-.04em]">The personality behind our success story.</h2><Rule /><div className="mt-7 space-y-4 text-sm leading-7 text-[#53647a]"><p>Since the company was established in 1999, Supun Group of Companies has cultivated its status as a pioneer in the manufacturing and the trading business. Guided by our corporate creed of “Innovation &amp; Creativity”, we have continued to challenge ourselves to provide a wide range of products and services locally and internationally through technology transfers, human commitment and professionalism.</p><p>The business environment has experienced radical changes due to the rapid advancement of technology and natural environmental distresses. This has helped businesses to identify new opportunities and also challenged them with greater pressures for change in their approach. As a result, businesses continually change their conventional approach to a more agile, lean and forward-thinking structure in the perpetually changing environment.</p><p>We too are constantly challenged by these competitive forces, be it natural or man-made, facing them positively and proactively with our dedicated team is what we always strive for.</p><p>At Supun, I am proud to be a part of an excellent team, that has dedicated themselves to the success story of a proud Sri Lankan entity. We continue to challenge ourselves to seize every opportunity within our reach enabling us to enrich the lives of our stakeholders in our efforts to exceed their expectations. This has been the core of our success story and we strive to continue our journey in nurturing business goals through various new products and services in the future.</p></div><p className="mt-7 border-t border-[#102746]/10 pt-5 font-semibold">M.F.M. Kaleel <span className="ml-2 text-sm font-normal text-[#6b7889]">Chairman</span></p></article></AnimatedSection>
    </div></section>

    <section id="leadership" className="scroll-mt-24 bg-white py-14 md:py-20"><div className="container mx-auto px-4"><Label>Leadership team</Label><h2 className="mt-3 text-4xl font-semibold normal-case tracking-[-.04em]">Leading with experience.</h2><Rule /><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{leadership.map((person, index) => <AnimatedSection key={person.name} animation="fade" delay={(index % 4) * 40} duration={450} triggerOnce={false}><article className="h-full border border-[#102746]/10 bg-[#fbfaf7] p-5"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#e8edf3] text-[#315f9f]"><Users size={18} /></span><h3 className="mt-5 text-lg font-semibold normal-case leading-tight">{person.name}</h3><p className="mt-2 text-xs font-semibold uppercase leading-5 tracking-[.08em] text-[#947027]">{person.title}</p>{person.description && person.description !== "—" && <p className="mt-3 text-xs leading-5 text-[#68778a]">{person.description}</p>}</article></AnimatedSection>)}</div></div></section>

    <section id="direction" className="w-full scroll-mt-24 bg-white"><div className="grid w-full lg:grid-cols-[1.35fr_.65fr]"><div className="grid gap-px bg-[#d9d7d1] sm:grid-cols-2"><article className="bg-white px-6 py-10 sm:px-10 lg:px-16 xl:px-20"><Eye className="text-[#d79a22]" size={34} strokeWidth={1.6} /><Label>Vision</Label><h2 className="mt-3 text-2xl font-semibold normal-case">Innovate. Unleash and Excel.</h2><p className="mt-4 text-sm leading-6 text-[#637186]">To unleash the potential within us to transform the markets through innovation and exceed people’s expectations for a better tomorrow, through the goods and services which empower and enrich the lives of Sri Lankans.</p></article><article className="bg-white px-6 py-10 sm:px-10 lg:px-12 xl:px-16"><Target className="text-[#d79a22]" size={34} strokeWidth={1.6} /><Label>Mission</Label><h2 className="mt-3 text-2xl font-semibold normal-case">Superior thinking. Sustainable value.</h2><p className="mt-4 text-sm leading-6 text-[#637186]">To harness superior thinking in the creation of products and services that functionally enhance the livelihood of people, while remaining cautious in reducing our carbon footprint. We integrate sustainable practices across our operations while delivering exceptional value to our stakeholders.</p></article></div><div className="relative min-h-[360px]"><img src={manufacturingImage} alt="Sustainable local manufacturing" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#102746]/90 to-[#102746]/10" /><p className="absolute bottom-8 left-8 max-w-[230px] text-2xl font-medium leading-snug text-white">Sustainable solutions for generations.</p></div></div></section>

    <section id="journey" className="scroll-mt-24 bg-white py-14 md:py-20"><div className="container mx-auto px-4"><Label>Our journey</Label><h2 className="mt-3 text-4xl font-semibold normal-case tracking-[-.04em]">Progress through the years.</h2><Rule /><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{journey.map(([year, text], index) => <article key={year} className={`relative min-h-[170px] border border-[#102746]/10 bg-[#fbfaf7] p-5 transition duration-300 hover:-translate-y-1 hover:border-[#d79a22]/60 hover:shadow-[0_12px_30px_rgba(16,39,70,.08)] ${index % 2 === 1 ? "lg:mt-8" : "lg:mb-8"}`}><span className="absolute left-0 top-5 h-9 w-1 bg-[#d79a22]" /><strong className="block text-2xl font-semibold tracking-[-.04em] text-[#102746]">{year}</strong><p className="mt-3 text-xs leading-5 text-[#637186]">{text}</p></article>)}</div></div></section>

    <section className="bg-[#f4f2ed] py-14 md:py-20"><div className="container mx-auto px-4"><Label>Core values</Label><h2 className="mt-3 text-4xl font-semibold normal-case tracking-[-.04em]">What guides us.</h2><Rule /><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{coreValues.map((value, index) => { const Icon = valueIcons[index % valueIcons.length]; return <article key={value.title} className="min-h-[210px] bg-white p-6 text-center"><Icon className="mx-auto text-[#d79a22]" size={35} strokeWidth={1.5} /><h3 className="mt-5 text-xl font-semibold normal-case">{value.title}</h3><p className="mt-3 text-sm leading-6 text-[#657286]">{value.description}</p></article>; })}</div></div></section>

    <section className="bg-white py-14 md:py-20"><div className="container mx-auto px-4"><Label>Awards &amp; recognition</Label><h2 className="mt-3 text-4xl font-semibold normal-case tracking-[-.04em]">Recognition earned across the Group.</h2><p className="mt-4 max-w-3xl text-sm leading-6 text-[#637186]">Recognition earned across the Group, from national manufacturing certification to industry and hospitality awards.</p><Rule /><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{awards.map((item) => <article key={`${item.award}-${item.awardedTo}`} className="flex min-h-[190px] flex-col border border-[#102746]/10 bg-[#fbfaf7] p-5"><Award className="text-[#d79a22]" size={28} strokeWidth={1.5} /><h3 className="mt-4 text-base font-semibold normal-case leading-snug">{item.award}</h3><div className="mt-auto pt-5"><p className="text-sm font-semibold text-[#315f9f]">{item.awardedTo}</p><p className="mt-1 text-xs text-[#728093]">{item.givenBy}</p></div></article>)}</div></div></section>

    <section className="relative isolate overflow-hidden py-20 text-white md:py-24"><img src={hospitalityImage} alt="Sri Lanka at sunset" className="absolute inset-0 -z-20 h-full w-full object-cover" /><div className="absolute inset-0 -z-10 bg-[#102746]/78" /><div className="container mx-auto flex flex-col items-start justify-between gap-7 px-4 md:flex-row md:items-center"><h2 className="max-w-2xl text-4xl font-semibold normal-case leading-tight tracking-[-.04em] md:text-5xl">Building a stronger Sri Lanka, together.</h2><Link to="/companies" className="inline-flex items-center gap-3 bg-[#e2a630] px-7 py-4 font-semibold text-[#102746] transition hover:bg-[#efba50]">Explore our businesses <ArrowRight size={18} /></Link></div></section>
  </div>
);

export default About;
