import { ArrowRight, Award, Eye, Flag, Gem, Lightbulb, Target, Users } from "lucide-react";
import { Link } from "react-router-dom";
import Seo from "@/components/Seo";
import { AnimatedSection } from "@/components/AnimatedSection";
import chairmanImage from "@/assets/Chairman.png";
import heroCorporate from "@/assets/hero-corporate.jpg";
import retailStore from "@/assets/retail-store.jpg";
import manufacturingImage from "@/assets/sector-manufacturing-v2.jpg";
import hospitalityImage from "@/assets/sector-hospitality-v2.jpg";
import { awards, coreValues, journey, leadership } from "@/data/siteContent";

const stats = [["11", "Group companies"], ["300+", "Employees"], ["250+", "Distributors"]];
const valueIcons = [Gem, Users, Lightbulb, Flag];
const Label = ({ children }: { children: React.ReactNode }) => <p className="text-xs font-bold uppercase tracking-[.18em] text-[#315f9f]">{children}</p>;
const Rule = () => <div className="mt-4 h-0.5 w-12 bg-[#d79a22]" />;

const About = () => (
  <div className="min-h-screen overflow-hidden bg-[#fbfaf7] text-[#102746]">
    <Seo title="About Supun Group of Companies | Our Story Since 1978" description="Discover the story, leadership, vision, journey and values of Supun Group of Companies, a Sri Lankan family-run group with roots dating to 1978." keywords="Supun Group history, Mohamed Fareed, M.F.M. Kaleel, Sri Lanka manufacturing group, Supun Group leadership" />

    <section className="relative isolate min-h-[620px] overflow-hidden bg-[#102746] md:min-h-[690px]">
      <img src={heroCorporate} alt="A modern Sri Lankan business building" className="absolute inset-0 -z-20 h-full w-full object-cover" />
      <div className="absolute inset-0 -z-10 bg-gradient-to-r from-white via-white/90 to-white/5 md:via-white/70" />
      <div className="container mx-auto flex min-h-[620px] items-center px-4 pb-16 pt-36 md:min-h-[690px] md:pt-40">
        <AnimatedSection animation="fade" duration={550} triggerOnce={false}><div className="max-w-2xl"><Label>Our story continues</Label><h1 className="mt-5 text-5xl font-semibold normal-case leading-[1.03] tracking-[-.045em] sm:text-6xl md:text-7xl">Built in Sri Lanka.<br />For a brighter tomorrow.</h1><p className="mt-6 max-w-lg text-base leading-7 text-[#3e536e] md:text-lg">Two generations. Multiple industries. One unwavering commitment to quality, innovation and Sri Lankan pride.</p><Rule /></div></AnimatedSection>
      </div>
      <div className="absolute bottom-8 right-6 hidden border-l border-white/50 pl-5 text-[10px] font-bold uppercase leading-6 tracking-[.2em] text-white md:block">People<br />Products<br />Possibilities</div>
    </section>

    <section id="story" className="scroll-mt-24 bg-white py-14 md:py-20"><div className="container mx-auto grid gap-10 px-4 lg:grid-cols-[.9fr_1.1fr] lg:items-center">
      <AnimatedSection animation="fade" duration={500} triggerOnce={false}><Label>Our story</Label><h2 className="mt-3 text-4xl font-semibold normal-case tracking-[-.04em] md:text-5xl">From trading goods to making them.</h2><Rule /><div className="mt-6 space-y-4 text-sm leading-7 text-[#53647a] md:text-base"><p>Supun Group began in 1978 when Mohamed Fareed founded Supun Traders in Colombo, supplying household goods to Sri Lankan homes.</p><p>In 1999, M.F.M. Kaleel took over the family business and formalised the Group, beginning its transition from trading to manufacturing.</p><p>Today, the Group works across manufacturing, retail, distribution and hospitality—united by quality, local capability and long-term value.</p></div><div className="mt-7 grid grid-cols-3 gap-3">{stats.map(([value, label]) => <div key={label} className="border-l-2 border-[#d79a22] pl-3"><strong className="text-2xl font-semibold md:text-3xl">{value}</strong><p className="mt-1 text-[10px] uppercase tracking-wide text-[#6a788a]">{label}</p></div>)}</div></AnimatedSection>
      <AnimatedSection animation="fade" duration={550} triggerOnce={false}><div className="relative mx-auto max-w-2xl pb-10 pl-4 sm:pl-12"><img src={retailStore} alt="The Group's retail beginnings" className="h-[300px] w-[78%] -rotate-2 border-[8px] border-white object-cover shadow-xl grayscale" /><img src={heroCorporate} alt="Supun Group today" className="absolute bottom-0 right-0 h-[220px] w-[58%] rotate-3 border-[8px] border-white object-cover shadow-xl" /><div className="absolute right-2 top-1 rounded-full bg-[#f3ead9] px-5 py-4 text-center text-[10px] font-bold uppercase leading-5 tracking-[.12em] text-[#8b682a]">From Sri Lanka<br />to Sri Lankans</div></div></AnimatedSection>
    </div></section>

    <section id="chairman" className="scroll-mt-24 bg-[#f4f2ed]"><div className="container mx-auto grid lg:grid-cols-[.72fr_1.28fr]">
      <AnimatedSection animation="fade" duration={500} triggerOnce={false}><div className="relative flex h-full min-h-[530px] items-end justify-center overflow-hidden bg-[#d9d4cb] px-6 pt-8"><img src={chairmanImage} alt="M.F.M. Kaleel, Chairman" className="max-h-[510px] w-full object-contain object-bottom" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#102746] via-[#102746]/80 to-transparent px-8 pb-7 pt-24 text-white"><p className="max-w-xs text-2xl font-medium leading-snug">“Innovation and creativity for a better tomorrow.”</p><p className="mt-5 text-sm font-semibold">M.F.M. Kaleel</p><p className="text-xs text-white/60">Chairman</p></div></div></AnimatedSection>
      <AnimatedSection animation="fade" duration={550} triggerOnce={false}><article className="flex h-full flex-col justify-center bg-white p-7 sm:p-10 lg:p-14"><Label>Chairman’s message</Label><h2 className="mt-3 text-4xl font-semibold normal-case tracking-[-.04em]">The people behind our progress.</h2><Rule /><div className="mt-7 space-y-4 text-sm leading-7 text-[#53647a] md:text-base"><p>Since the Group was formalised in 1999, we have worked to build a trusted name in manufacturing and trading through innovation, commitment and professionalism.</p><p>Markets and technology continue to change. We meet those changes positively, supported by a team dedicated to useful products, dependable services and lasting value.</p><p>Our success belongs to the people who have carried this Sri Lankan business forward. Together, we will continue enriching the lives of our customers, employees and partners.</p></div><p className="mt-7 border-t border-[#102746]/10 pt-5 font-semibold">M.F.M. Kaleel <span className="ml-2 text-sm font-normal text-[#6b7889]">Chairman</span></p></article></AnimatedSection>
    </div></section>

    <section id="leadership" className="scroll-mt-24 bg-white py-14 md:py-20"><div className="container mx-auto px-4"><Label>Leadership team</Label><h2 className="mt-3 text-4xl font-semibold normal-case tracking-[-.04em]">Leading with experience.</h2><Rule /><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{leadership.map((person, index) => <AnimatedSection key={person.name} animation="fade" delay={(index % 4) * 40} duration={450} triggerOnce={false}><article className="h-full border border-[#102746]/10 bg-[#fbfaf7] p-5"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#e8edf3] text-[#315f9f]"><Users size={18} /></span><h3 className="mt-5 text-lg font-semibold normal-case leading-tight">{person.name}</h3><p className="mt-2 text-xs font-semibold uppercase leading-5 tracking-[.08em] text-[#947027]">{person.title}</p>{person.description && person.description !== "—" && <p className="mt-3 line-clamp-3 text-xs leading-5 text-[#68778a]">{person.description}</p>}</article></AnimatedSection>)}</div></div></section>

    <section id="direction" className="scroll-mt-24 bg-[#f4f2ed]"><div className="container mx-auto grid lg:grid-cols-[1.35fr_.65fr]"><div className="grid gap-px bg-[#d9d7d1] sm:grid-cols-2"><article className="bg-white p-8 md:p-10"><Eye className="text-[#d79a22]" size={34} strokeWidth={1.6} /><Label>Vision</Label><h2 className="mt-3 text-2xl font-semibold normal-case">Innovate. Unleash and Excel.</h2><p className="mt-4 text-sm leading-6 text-[#637186]">To transform markets through innovation and exceed expectations with goods and services that empower Sri Lankan lives.</p></article><article className="bg-white p-8 md:p-10"><Target className="text-[#d79a22]" size={34} strokeWidth={1.6} /><Label>Mission</Label><h2 className="mt-3 text-2xl font-semibold normal-case">Sustainable value.</h2><p className="mt-4 text-sm leading-6 text-[#637186]">To create useful products and services responsibly while delivering exceptional value to every stakeholder.</p></article></div><div className="relative min-h-[330px]"><img src={manufacturingImage} alt="Sustainable local manufacturing" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#102746]/90 to-[#102746]/10" /><p className="absolute bottom-8 left-8 max-w-[230px] text-2xl font-medium leading-snug text-white">Sustainable solutions for generations.</p></div></div></section>

    <section id="journey" className="scroll-mt-24 bg-white py-14 md:py-20"><div className="container mx-auto px-4"><Label>Our journey</Label><h2 className="mt-3 text-4xl font-semibold normal-case tracking-[-.04em]">Progress through the years.</h2><Rule /><div className="mt-9 overflow-x-auto pb-4"><div className="relative flex min-w-[1050px] before:absolute before:left-2 before:right-5 before:top-[9px] before:h-px before:bg-[#d79a22]">{journey.map(([year, text]) => <article key={year} className="relative w-[170px] shrink-0 pr-5"><span className="block h-[19px] w-[19px] rounded-full border-[5px] border-white bg-[#d79a22] shadow" /><strong className="mt-4 block text-lg">{year}</strong><p className="mt-2 text-xs leading-5 text-[#637186]">{text}</p></article>)}</div></div></div></section>

    <section className="bg-[#f4f2ed] py-14 md:py-20"><div className="container mx-auto px-4"><Label>Core values</Label><h2 className="mt-3 text-4xl font-semibold normal-case tracking-[-.04em]">What guides us.</h2><Rule /><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{coreValues.map((value, index) => { const Icon = valueIcons[index % valueIcons.length]; return <article key={value.title} className="min-h-[210px] bg-white p-6 text-center"><Icon className="mx-auto text-[#d79a22]" size={35} strokeWidth={1.5} /><h3 className="mt-5 text-xl font-semibold normal-case">{value.title}</h3><p className="mt-3 text-sm leading-6 text-[#657286]">{value.description}</p></article>; })}</div></div></section>

    <section className="bg-white py-14 md:py-20"><div className="container mx-auto px-4"><Label>Awards &amp; recognition</Label><h2 className="mt-3 text-4xl font-semibold normal-case tracking-[-.04em]">Recognition earned across the Group.</h2><Rule /><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{awards.map((item) => <article key={`${item.award}-${item.awardedTo}`} className="flex min-h-[190px] flex-col border border-[#102746]/10 bg-[#fbfaf7] p-5"><Award className="text-[#d79a22]" size={28} strokeWidth={1.5} /><h3 className="mt-4 text-base font-semibold normal-case leading-snug">{item.award}</h3><div className="mt-auto pt-5"><p className="text-sm font-semibold text-[#315f9f]">{item.awardedTo}</p><p className="mt-1 text-xs text-[#728093]">{item.givenBy}</p></div></article>)}</div></div></section>

    <section className="relative isolate overflow-hidden py-20 text-white md:py-24"><img src={hospitalityImage} alt="Sri Lanka at sunset" className="absolute inset-0 -z-20 h-full w-full object-cover" /><div className="absolute inset-0 -z-10 bg-[#102746]/78" /><div className="container mx-auto flex flex-col items-start justify-between gap-7 px-4 md:flex-row md:items-center"><h2 className="max-w-2xl text-4xl font-semibold normal-case leading-tight tracking-[-.04em] md:text-5xl">Building a stronger Sri Lanka, together.</h2><Link to="/companies" className="inline-flex items-center gap-3 bg-[#e2a630] px-7 py-4 font-semibold text-[#102746] transition hover:bg-[#efba50]">Explore our businesses <ArrowRight size={18} /></Link></div></section>
  </div>
);

export default About;
