import { Link } from "react-router-dom";
import { Mail, MapPin, Phone } from "lucide-react";
import logo from "@/assets/supun-group-of-companies-logo.png";

const Footer = () => {
  const currentYear = new Date().getFullYear();
  return <footer className="bg-primary-dark text-white"><div className="container mx-auto px-4 py-14"><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-10"><div className="lg:col-span-2"><Link to="/" className="inline-block bg-white p-3 rounded-lg mb-5"><img src={logo} alt="Supun Group of Companies" className="h-14 w-auto" /></Link><p className="text-white/75 max-w-xl leading-relaxed">A family-run Sri Lankan group with roots dating to 1978, operating across manufacturing, retail, distribution and hospitality.</p><div className="mt-5 space-y-2 text-sm"><a href="mailto:info@supungroup.lk" className="flex items-center gap-2 hover:text-accent"><Mail size={16} /> info@supungroup.lk</a><a href="tel:+94112055026" className="flex items-center gap-2 hover:text-accent"><Phone size={16} /> +94 112 055 026</a><div className="flex items-center gap-2 text-white/75"><MapPin size={16} /> Colombo, Sri Lanka</div></div></div><div><h2 className="text-lg normal-case mb-4">Quick Links</h2><ul className="space-y-2 text-white/75"><li><Link to="/about" className="hover:text-accent">About Us</Link></li><li><Link to="/companies" className="hover:text-accent">Our Companies</Link></li><li><Link to="/camy-products" className="hover:text-accent">Camy Products</Link></li><li><Link to="/careers" className="hover:text-accent">Careers</Link></li><li><Link to="/news" className="hover:text-accent">News & Media</Link></li><li><Link to="/contact" className="hover:text-accent">Contact</Link></li></ul></div><div><h2 className="text-lg normal-case mb-4">Our Vision</h2><p className="text-accent font-semibold text-lg">“Innovate. Unleash and Excel.”</p><p className="text-white/65 text-sm mt-4">Built in Sri Lanka. Built to Last.</p></div></div><div className="border-t border-white/15 mt-10 pt-7 flex flex-col sm:flex-row gap-3 justify-between text-sm text-white/60"><p>© {currentYear} Supun Group of Companies. All rights reserved.</p><p>Website V2</p></div></div></footer>;
};

export default Footer;
