// AUTO-GENERATED by scripts/import-current-site-logos.mjs
// Sources: the existing public supuncompanies.com company/brand APIs.
export const companyLogos: Record<string, string> = {
  "supun-traders": "/logos/supun-traders.png",
  "supun-super-center": "/logos/supun-super-center.png",
  "supun-arcade-residency": "/logos/supun-arcade-residency.png",
  "supun-aerosoft": "/logos/supun-aerosoft.png",
  "aerostar-home-appliances": "/logos/aerostar-home-appliances.png",
  "camy-smart": "/logos/camy-smart.png",
  "rodsons": "/logos/rodsons.png",
  "new-camy-smart": "/logos/new-camy-smart.png",
  "camy-global": "/logos/camy-global.png"
};

export const getCompanyLogo = (companyId: string): string | undefined => companyLogos[companyId];
